### ISSUE TITLE
Having data and routes in an addon

### ISSUE THREAD

**Issue by serchavalos** [trentmwillis/engine-training#4]
Hi, @trentmwillis!

Regarding on this comment taken from the `README.md` file

> Note: in general, you would not define application-specific constructs (such as mock data and routes) in an addon, but since these will eventually become Engines, it is okay.

Is the idea that the host app will own the routes and data/adapters of the whole app?

Regards,

// Sergio

**Comment by trentmwillis** [comment]
The host app should have all the routes/data/adapters for the application, _except_ when using engines. Since Engines are isolated, it makes since that those things can live with the Engine itself.

Hope that makes it clearer. If not, I'd recommend jumping into the Ember Community Slack for further questions about Engines as I'm not actively maintaining this repo.
